Repository recodehive/Opensource-practice, pull requests merged in 2024-08, with the labels that each got.

#79 Unmerged PRs
  pr_dump/redame.md
Labels: gssoc, level 3

#73 MastanSayyad - Open Pending PRs
  pr_dump/Open PRs - MastanSayyad.md
Labels: gssoc, level 3

#71 PR given
  pr_dump/image-1.png
  pr_dump/image.png
  pr_dump/prLinks.md
Labels: gssoc, level 3

#69 Create Eduford-university
  pr_dump/Eduford-university
Labels: gssoc, level 2

#68 Create File -Pedning PR merge links.md
  pr_dump/File -Pedning PR merge links.md
Labels: gssoc, level 2

#80 Unmerged PR
  pr_dump/redame.md
Labels: gssoc, level2

#81 Open PRs - MastanSayyad PR -2
  pr_dump/Open PRs - MastanSayyad.md
Labels: level2

#64 Create File-1.md
  pr_dump/File-1.md
Labels: gssoc, level2

#86 Links of prs pending from a long time .
  pr_dump/Pending PR merge links.md
Labels: gssoc, level2

#85 Create vishanurag.md
  pr_dump/vishanurag.md
Labels: gssoc, level2

#84 RadhikaMalpani1702 Open PR list
  pr_dump/Open PR Radhika Malpani.md
Labels: gssoc, level3

#83 Open Prs - Asmita Mishra
  pr_dump/Open PR - Asmita Mishra
Labels: gssoc, level3

#82 Pending Open PR
  pr_dump/Pending Open PR
Labels: gssoc, level3

#92 Unmerged PR (vivekvardhan2810)
  pr_dump/unmerged prs.md
Labels: gssoc, level2

#104 Pending pr not merged
  pr_dump/PR not merged- ananyag309/README.md
Labels: gssoc, level3

#103 Create hemashree21
  pr_dump/hemashree21
Labels: gssoc, level2

#102 Create Hemashree21
  pr_dump/Hemashree21
Labels: gssoc, level1

#100 Old PR[Nest ONDC]
  pr_dump/Old PR[Nest ONDC]
Labels: gssoc, level2

#96 Unmerged PR
  pr_dump/unmerged pr
Labels: gssoc, level2

#97 Create jency1 - unmerged PR's
  pr_dump/jency1 - unmerged PR's
Labels: gssoc, level3

#93 Create Saksham.md
  pr_dump/Saksham.md
Labels: gssoc, level3

#106 Added Open PR.md
  Open PR.md
Labels: gssoc, level2

#107 Create Open PR - ayush848.md
  pr_dump/Open PR - ayush848.md
Labels: gssoc, level2

#120 Create OpenPR.md
  OpenPr.md
Labels: gssoc, level2

#118 Pending PR - Utsavladia
  pr_dump/Pending PR - Utsavladia
Labels: gssoc, level3

#117 Unmerged PRs
  pr_dump/vijayshankersharma.md
Labels: gssoc, level2

#116 Added unmerged PR
  pr_dump/vishanurag.md
Labels: gssoc, level2

#114 pr not merged
  pr_dump/old or
Labels: gssoc, level2

#113 open PR
  pr_dump/open PR
Labels: gssoc, level2

#112 unmerged PR
  pr_dump/unmerged PR
Labels: gssoc, level3

#111 pr not merged
  pr_dump/pr not merged
Labels: gssoc, level2

#110 PR not merged
  pr_dump/PR not merged
Labels: gssoc, level2

#109 Create PR not merged - jency1
  pr_dump/PR not merged
Labels: gssoc, level2

#129 Open PRs - Asmita Mishra
  pr_dump/Open PR - Asmita Mishra
Labels: gssoc, level2

#128 open-PR-request to merge
  Open-pr.md
Labels: gssoc, level2

#127 My PR not Merged
  pr_dump/open-pr-zalabhavy
Labels: gssoc, level2

#131 ShouryaMishra2006 PR not merged
  pr_dump/PR not merged-ShouryaMishra2006/unmergedpr.md
Labels: gssoc, level2

#90 Open valid PRs for a long period of time
  pr_dump/Open PR - Vinisha Dsouza.md
Labels: gssoc, level3

#133 PR's not merged #132
  Open_PR.md
  pr_dump/Hemashree21
  pr_dump/PR not merged
  pr_dump/Pending Open PR
  pr_dump/unmerged PR
Labels: gssoc, level3

#138 Devlabs PR not merged
  pr_dump/Open PR - Hars-21.md
Labels: gssoc, level3

#139 pr not merged
  pr_dump/PR not merged-Amrutha Pariprolu/file1.md
Labels: gssoc, level2

#122 PR not merged
  pr_dump/redame.md
Labels: gssoc, level3

#124 Create Pending merged PR's - Praneeth-2602.mg
  pr_dump/Pending Open PR's - Praneeth-2602.mg
Labels: gssoc, level2

#150 not merged
  pr_dump/unmerged_pr.md
Labels: gssoc, level2

#146 PR not merged-BHS-Harish
  pr_dump/PR not merged-BHS-Harish
Labels: gssoc, level2

#145 Open PRs- Sau-mili
  pr_dump/Open PRs- sau-mili
Labels: gssoc, level2
